name: susu
description: A new Flutter project

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_native_splash: ^2.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10 

  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  go_router: ^17.2.3
  
  
  sign_in_with_apple: ^8.1.0
  google_sign_in: ^6.2.1
  mockito: ^5.6.4
  google_fonts: ^8.1.0
  provider: ^6.1.2
  http: ^1.6.0
  url_launcher: ^6.3.2
  flutter_signin_button: ^2.1.1
  google_sign_in_dartio: ^0.3.0
  firebase_messaging: ^16.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/final.jpg
    - assets/images/atom.png
    - assets/images/g_logo.png
    - assets/images/arrow-left.svg
    - assets/404.json
    - assets/loading.json
    - assets/images/profileImage.jpg
    - assets/icons/arrowforprofile.png
    - assets/icons/user-circle.png
    - assets/icons/shield.png
    - assets/icons/money.png
    - assets/icons/taxes.png
    - assets/icons/cash.png
    - assets/icons/accessibility.png
    - assets/icons/caret-right.svg
    - assets/images/add_money.png
    - assets/icons/house.svg
    - assets/icons/list.svg
    - assets/icons/bell.svg
    - assets/icons/scroll.svg
    - assets/icons/user.svg
    - assets/images/money_transfer.png
    - assets/icons/plus.svg
    - assets/icons/receipt.svg
    - assets/icons/money-wavy.svg
    - assets/icons/wallet.svg
    - assets/icons/envelope.svg
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/final.jpg
  android: true
  ios: true
